/**
 * Seeds 3 Lagos property hosts + 1 guest and 15 ACTIVE listings across Lagos, Nigeria.
 * Run: npx tsx scripts/seed-property-lagos.ts
 */
import "dotenv/config"
import { PrismaClient } from "@prisma/client"
import {
  type CitySeedConfig,
  type PropertyListingSeed,
  upsertPropertyHost,
  upsertPropertyListing,
  upsertSeedUser,
} from "./seed-property-helpers"

const prisma = new PrismaClient()

const LAGOS: CitySeedConfig = {
  city: "Lagos",
  state: "Lagos",
  country: "Nigeria",
  zip: "100001",
  centerLat: 6.5244,
  centerLng: 3.3792,
}

const CUSTOMER = {
  email: "lagos.guest@killo.test",
  phone: "+234809999001",
  name: "Amara Okafor",
}

const HOSTS = [
  {
    email: "lagos.host1@killo.test",
    phone: "+234801111001",
    name: "Chioma Adeyemi",
    businessName: "VI Prime Hospitality",
    suffix: "h1",
    description: "Luxury island stays across Victoria Island, Ikoyi, and Eko Atlantic.",
  },
  {
    email: "lagos.host2@killo.test",
    phone: "+234801111002",
    name: "Tunde Bakare",
    businessName: "Lekki Coastal Estates",
    suffix: "h2",
    description: "Waterfront villas and premium apartments on the Lekki corridor.",
  },
  {
    email: "lagos.host3@killo.test",
    phone: "+234801111003",
    name: "Ngozi Okonkwo",
    businessName: "Mainland Comfort Stays",
    suffix: "h3",
    description: "Reliable business and family homes across mainland Lagos.",
  },
]

/** Curated Unsplash sets — varied interiors, exteriors, and amenities */
const IMAGES = {
  luxuryHotel: [
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80",
    "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
  ],
  modernApartment: [
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
    "https://images.unsplash.com/photo-1560448204-e02f11c2d0ef?w=1200&q=80",
  ],
  penthouse: [
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
    "https://images.unsplash.com/photo-1600047509807-ba8f8d4dc51a?w=1200&q=80",
    "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80",
  ],
  beachVilla: [
    "https://images.unsplash.com/photo-1611892440504-42a784e74f137?w=1200&q=80",
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
  ],
  islandMansion: [
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80",
    "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80",
  ],
  familyHome: [
    "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
    "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80",
    "https://images.unsplash.com/photo-1600210492496-724fe5c67fb0?w=1200&q=80",
  ],
  loft: [
    "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
    "https://images.unsplash.com/photo-1600573472591-ee5b8d3f32d1?w=1200&q=80",
    "https://images.unsplash.com/photo-1600210492482-03d692cde8da?w=1200&q=80",
  ],
  resort: [
    "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80",
    "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=80",
    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=80",
  ],
  businessHotel: [
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=80",
    "https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?w=1200&q=80",
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=80",
  ],
}

const LISTINGS_BY_HOST: Array<{ suffix: string; listings: PropertyListingSeed[] }> = [
  {
    suffix: "h1",
    listings: [
      {
        title: "Eko Signature Suite VI",
        tagline: "Skyline views above Ahmadu Bello Way",
        type: "HOTEL",
        categorySlug: "luxury-hotel",
        area: "Victoria Island",
        address: "1415 Ahmadu Bello Way, Victoria Island, Lagos",
        lat: 6.4281,
        lng: 3.4219,
        nightlyRate: 185000,
        cleaningFee: 8000,
        securityDeposit: 50000,
        discountPercent: 10,
        amenities: ["wifi", "pool", "gym", "restaurant", "concierge", "parking"],
        images: IMAGES.luxuryHotel,
        badge: "Editor's Choice",
        guestTier: "Platinum",
        rating: 4.91,
        reviewCount: 124,
        sqm: 65,
        bedrooms: 1,
        beds: 1,
        masterBeds: 1,
        maxAdults: 2,
        maxChildren: 1,
        maxInfants: 1,
        tourUrl: "https://my.matterport.com/show/?m=sample",
      },
      {
        title: "Ikoyi Bridge View Apartment",
        tagline: "Panoramic Lekki-Ikoyi Link views",
        type: "APARTMENT",
        categorySlug: "apartment",
        area: "Ikoyi",
        address: "Bourdillon Road, Ikoyi, Lagos",
        lat: 6.4541,
        lng: 3.4316,
        nightlyRate: 95000,
        amenities: ["wifi", "gym", "power", "parking"],
        images: IMAGES.modernApartment,
        badge: "Top Rated",
        guestTier: "Standard",
        rating: 4.86,
        reviewCount: 67,
        sqm: 110,
        bedrooms: 2,
        beds: 2,
        masterBeds: 1,
        maxAdults: 4,
        maxChildren: 2,
        maxInfants: 1,
      },
      {
        title: "Atlantic City Penthouse",
        tagline: "Private terrace on the new coastline",
        type: "VILLA",
        categorySlug: "penthouse",
        area: "Eko Atlantic",
        address: "Eko Atlantic City, Victoria Island Extension, Lagos",
        lat: 6.4162,
        lng: 3.408,
        nightlyRate: 420000,
        cleaningFee: 15000,
        securityDeposit: 120000,
        amenities: ["wifi", "pool", "spa", "butler", "parking", "chef"],
        images: IMAGES.penthouse,
        badge: "Ultra Luxury",
        guestTier: "VIP",
        rating: 4.98,
        reviewCount: 38,
        sqm: 320,
        bedrooms: 4,
        beds: 5,
        masterBeds: 2,
        maxAdults: 8,
        maxChildren: 4,
        maxInfants: 2,
        hasOceanfront: true,
        hasGatedCommunity: true,
        gatePin: "8842",
        requireGuidedSelfie: true,
      },
      {
        title: "Federal Palace Wing",
        tagline: "Classic hospitality near the marina",
        type: "HOTEL",
        categorySlug: "business-hotel",
        area: "Victoria Island",
        address: "6-8 Ahmadu Bello Way, Victoria Island, Lagos",
        lat: 6.4265,
        lng: 3.4188,
        nightlyRate: 145000,
        amenities: ["wifi", "pool", "restaurant", "gym", "concierge"],
        images: IMAGES.businessHotel,
        badge: "Heritage",
        guestTier: "Platinum",
        rating: 4.79,
        reviewCount: 203,
        sqm: 55,
        bedrooms: 1,
        beds: 1,
        maxAdults: 2,
        maxChildren: 1,
      },
      {
        title: "Ikoyi Executive Studio",
        tagline: "Walk to embassies and business district",
        type: "APARTMENT",
        categorySlug: "studio",
        area: "Ikoyi",
        address: "Gerrard Road, Ikoyi, Lagos",
        lat: 6.4512,
        lng: 3.4358,
        nightlyRate: 72000,
        discountPercent: 5,
        amenities: ["wifi", "power", "parking"],
        images: IMAGES.modernApartment,
        badge: "Business",
        rating: 4.74,
        reviewCount: 45,
        sqm: 48,
        bedrooms: 1,
        beds: 1,
        maxAdults: 2,
      },
    ],
  },
  {
    suffix: "h2",
    listings: [
      {
        title: "Lekki Phase 1 Beach House",
        tagline: "Steps from the Atlantic shore",
        type: "VILLA",
        categorySlug: "beach-villa",
        area: "Lekki Phase 1",
        address: "Admiralty Way, Lekki Phase 1, Lagos",
        lat: 6.4474,
        lng: 3.472,
        nightlyRate: 280000,
        cleaningFee: 12000,
        securityDeposit: 80000,
        amenities: ["wifi", "pool", "beachfront", "parking", "chef"],
        images: IMAGES.beachVilla,
        badge: "Beachfront",
        guestTier: "VIP",
        rating: 4.95,
        reviewCount: 52,
        sqm: 240,
        bedrooms: 3,
        beds: 4,
        masterBeds: 1,
        maxAdults: 6,
        maxChildren: 3,
        maxInfants: 2,
        hasOceanfront: true,
        hasGatedCommunity: true,
        gatePin: "3310",
      },
      {
        title: "Banana Island Mansion",
        tagline: "Nigeria's most exclusive address",
        type: "VILLA",
        categorySlug: "mansion",
        area: "Banana Island",
        address: "Banana Island, Ikoyi, Lagos",
        lat: 6.4412,
        lng: 3.4087,
        nightlyRate: 550000,
        cleaningFee: 20000,
        securityDeposit: 200000,
        amenities: ["wifi", "pool", "spa", "butler", "chef", "parking", "gym"],
        images: IMAGES.islandMansion,
        badge: "Signature",
        guestTier: "VIP",
        rating: 4.99,
        reviewCount: 29,
        sqm: 450,
        bedrooms: 5,
        beds: 6,
        masterBeds: 2,
        maxAdults: 10,
        maxChildren: 4,
        maxInfants: 2,
        hasGatedCommunity: true,
        hasOceanfront: true,
        gatePin: "9921",
        requireGuidedSelfie: true,
      },
      {
        title: "Lekki Admiralty Waterfront",
        tagline: "Marina lifestyle with city convenience",
        type: "APARTMENT",
        categorySlug: "waterfront",
        area: "Lekki Phase 1",
        address: "Admiralty Way Waterfront, Lekki, Lagos",
        lat: 6.4428,
        lng: 3.4562,
        nightlyRate: 118000,
        amenities: ["wifi", "gym", "pool", "parking", "power"],
        images: IMAGES.modernApartment,
        badge: "Popular",
        rating: 4.83,
        reviewCount: 88,
        sqm: 135,
        bedrooms: 3,
        beds: 3,
        masterBeds: 1,
        maxAdults: 5,
        maxChildren: 2,
      },
      {
        title: "Landmark Beach Resort Suite",
        tagline: "Resort pool and private beach access",
        type: "HOTEL",
        categorySlug: "resort",
        area: "Oniru",
        address: "Water Corporation Road, Oniru, Victoria Island, Lagos",
        lat: 6.4198,
        lng: 3.4312,
        nightlyRate: 165000,
        amenities: ["wifi", "pool", "beachfront", "restaurant", "spa"],
        images: IMAGES.resort,
        badge: "Resort",
        guestTier: "Platinum",
        rating: 4.88,
        reviewCount: 156,
        sqm: 72,
        bedrooms: 1,
        beds: 1,
        masterBeds: 1,
        maxAdults: 2,
        maxChildren: 2,
        hasOceanfront: true,
      },
      {
        title: "Lekki Conservation Villa",
        tagline: "Nature retreat minutes from the city",
        type: "VILLA",
        categorySlug: "eco-villa",
        area: "Lekki",
        address: "Lekki Conservation Centre Road, Lekki, Lagos",
        lat: 6.4419,
        lng: 3.5354,
        nightlyRate: 198000,
        amenities: ["wifi", "pool", "parking", "power"],
        images: IMAGES.beachVilla,
        badge: "Eco Retreat",
        rating: 4.77,
        reviewCount: 41,
        sqm: 200,
        bedrooms: 3,
        beds: 3,
        masterBeds: 1,
        maxAdults: 6,
        maxChildren: 3,
        hasJungleView: true,
        hasGatedCommunity: true,
        gatePin: "4477",
      },
    ],
  },
  {
    suffix: "h3",
    listings: [
      {
        title: "Ikeja GRA Family Home",
        tagline: "Quiet leafy streets near the airport",
        type: "HOUSE",
        categorySlug: "family-home",
        area: "Ikeja GRA",
        address: "Joel Ogunnaike Street, Ikeja GRA, Lagos",
        lat: 6.5834,
        lng: 3.3519,
        nightlyRate: 85000,
        amenities: ["wifi", "parking", "power", "garden"],
        images: IMAGES.familyHome,
        badge: "Family Friendly",
        rating: 4.81,
        reviewCount: 73,
        sqm: 180,
        bedrooms: 3,
        beds: 4,
        masterBeds: 1,
        maxAdults: 6,
        maxChildren: 4,
        maxInfants: 2,
        hasGatedCommunity: true,
        gatePin: "2201",
      },
      {
        title: "Yaba Tech Hub Loft",
        tagline: "Creative loft near innovation district",
        type: "APARTMENT",
        categorySlug: "loft",
        area: "Yaba",
        address: "Herbert Macaulay Way, Yaba, Lagos",
        lat: 6.5095,
        lng: 3.3711,
        nightlyRate: 55000,
        discountPercent: 8,
        amenities: ["wifi", "power", "parking"],
        images: IMAGES.loft,
        badge: "Trending",
        rating: 4.72,
        reviewCount: 94,
        sqm: 85,
        bedrooms: 1,
        beds: 1,
        maxAdults: 2,
        maxChildren: 1,
      },
      {
        title: "Surulere Stadium View Apartment",
        tagline: "Sports district with skyline views",
        type: "APARTMENT",
        categorySlug: "apartment",
        area: "Surulere",
        address: "National Stadium Surulere, Lagos",
        lat: 6.4969,
        lng: 3.355,
        nightlyRate: 48000,
        amenities: ["wifi", "power", "parking"],
        images: IMAGES.modernApartment,
        badge: "Value Pick",
        rating: 4.68,
        reviewCount: 56,
        sqm: 95,
        bedrooms: 2,
        beds: 2,
        maxAdults: 4,
        maxChildren: 2,
      },
      {
        title: "Maryland Business Hotel",
        tagline: "Corporate corridor with fast airport access",
        type: "HOTEL",
        categorySlug: "business-hotel",
        area: "Maryland",
        address: "Ikorodu Road, Maryland, Lagos",
        lat: 6.5789,
        lng: 3.3676,
        nightlyRate: 92000,
        amenities: ["wifi", "gym", "restaurant", "parking", "concierge"],
        images: IMAGES.businessHotel,
        badge: "Business",
        guestTier: "Platinum",
        rating: 4.76,
        reviewCount: 112,
        sqm: 42,
        bedrooms: 1,
        beds: 1,
        maxAdults: 2,
      },
      {
        title: "Apapa Portside Guest House",
        tagline: "Industrial hub accommodation",
        type: "HOUSE",
        categorySlug: "guest-house",
        area: "Apapa",
        address: "Warehouse Road, Apapa, Lagos",
        lat: 6.4488,
        lng: 3.359,
        nightlyRate: 42000,
        amenities: ["wifi", "power", "parking"],
        images: IMAGES.familyHome,
        badge: "Budget Plus",
        rating: 4.55,
        reviewCount: 28,
        sqm: 140,
        bedrooms: 2,
        beds: 3,
        maxAdults: 4,
        maxChildren: 2,
      },
    ],
  },
]

async function main() {
  const password = process.env.PROPERTY_SEED_PASSWORD || "Killo@1234"

  const customer = await upsertSeedUser(prisma, { ...CUSTOMER, role: "CUSTOMER", password })
  console.log(`Guest: ${customer.email}`)

  let totalListings = 0

  for (let h = 0; h < HOSTS.length; h++) {
    const hostDef = HOSTS[h]
    const host = await upsertPropertyHost(prisma, {
      host: hostDef,
      password,
      businessName: hostDef.businessName,
      cityConfig: LAGOS,
      description: hostDef.description,
    })

    const pack = LISTINGS_BY_HOST[h]
    for (const listing of pack.listings) {
      await upsertPropertyListing(prisma, {
        idPrefix: "lag",
        hostSuffix: pack.suffix,
        vendorId: host.id,
        listing,
        cityConfig: LAGOS,
      })
      totalListings++
    }
    console.log(`Host ${host.email}: ${pack.listings.length} listings in Lagos`)
  }

  console.log(`\nDone — ${totalListings} Lagos listings seeded.`)
  console.log("Login: PROPERTY_SEED_PASSWORD (default Killo@1234)")
  console.log("View in app: Property → tap Lagos destination")
  console.log("API: GET /api/property/listings?city=Lagos&status=ACTIVE")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
